# Étape 1 : Build avec Node
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Étape 2 : Serveur léger (Nginx) pour servir les fichiers statiques
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Optionnel : copier une conf nginx si tu as du routing React
# COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
